"""add ephemeral cert support

Revision ID: 17b3643ffd8a
Revises: 9256dfafa545
Create Date: 2026-04-29 17:59:40.431348
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b3643ffd8a'
down_revision: Union[str, None] = '9256dfafa545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add ephemeral_cert to the credential type enum
    op.execute("ALTER TYPE credentialtype ADD VALUE IF NOT EXISTS 'EPHEMERAL_CERT'")
    # Add cert_validity_hours column
    op.add_column('credentials', sa.Column('cert_validity_hours', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'cert_validity_hours')
    # ### end Alembic commands ###
