"""add cert auth fields to servers

Revision ID: 9a9138065c97
Revises: a7f799e5a2b0
Create Date: 2026-04-30 09:17:58.781717
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9138065c97'
down_revision: Union[str, None] = 'a7f799e5a2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ssh_username', sa.String(length=255), nullable=True))
    op.add_column('servers', sa.Column('cert_auth_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'cert_auth_enabled')
    op.drop_column('servers', 'ssh_username')
    # ### end Alembic commands ###
