"""rename cert_validity_hours to cert_validity_minutes

Revision ID: eb29b744b69c
Revises: 17b3643ffd8a
Create Date: 2026-04-29 18:25:01.102038
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb29b744b69c'
down_revision: Union[str, None] = '17b3643ffd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('credentials', 'cert_validity_hours', new_column_name='cert_validity_minutes')
    # Convert existing hours to minutes
    op.execute("UPDATE credentials SET cert_validity_minutes = cert_validity_minutes * 60 WHERE cert_validity_minutes IS NOT NULL AND cert_validity_minutes < 25")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('cert_validity_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('credentials', 'cert_validity_minutes')
    # ### end Alembic commands ###
